pipeline {

    agent any

    environment {
        APP_NAME = "AirlineReservationSystem"
        SERVER_IP = "13.234.20.226"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Deploy') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} '
                    sudo rm -rf Airline-webapp
                    git clone https://github.com/venkat01012004/Airline-webapp.git 
                    cd Airline-webapp/${APP_NAME}
                    mvn clean package
                   sudo cp target/${APP_NAME}.war /opt/tomcat/webapps/
                '
                """
            }
        }
    }
}
